name: Deploy Frontend
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 2. Login to Docker Hub
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Docker image bauen
      - run: docker build -t cygnetops/react-test -f Dockerfile.dev .

      # 4. Tests im Container ausführen
      - run: docker run -e CI=true cygnetops/react-test npm test